added klotho analysis
nanlabs/devops-reference pull request #106
Opened 2023-05-30 14:26 UTC by AgusPk

# What's this PR do?

- Added klotho analysis
- Added Readme with general information
- Added POC in go language
Solves #57 

@ulises-jeremias

<!--

Please title your PR as follows: `feature: fix foo bar`. 
Always start with the thing you are fixing, then describe the fix.
Don't use past tense (e.g. "fixed foo bar").

Explain what your PR does and why.

If you are adding a new function, please document it and add tests:

```
code you added/updated
```

If you are fixing a bug, please add a test that covers it.

Before submitting a PR, please:
  - specify the command to execute or steps to follow to know that the problem was solved

We try to process PRs as soon as possible. They should be handled within 24 hours.

Applying labels to PRs is not needed.

Thanks a lot for your contribution!

->

2023-05-31 07:27 UTC, ulises-jeremias requested changes
great work! I just requested some changes. I think we need to include a `.gitignore` for the `_compiled` directory before merging. You can do that first and then I'll review the README of the example again 😊

2023-05-31 07:27 UTC, ulises-jeremias commented on examples.json
> +      "tags": ["Examples > DevOps > Infrastructure > Pulumi > Klotho"],
we use the `tags` to generate the readme sections. I think this one fits better with the rest of the titles at awesome nan
 
```suggestion
      "tags": ["Examples > DevOps > Infrastructure from Code > Klotho and more!"],
```

2023-05-31 07:27 UTC, ulises-jeremias commented on examples/klotho-analysis/ANALYSIS.md
> +IMPORTANT - This analysis was made on 2023-05-16. The service was still in beta at that time.
```suggestion
> IMPORTANT - This analysis was made on 2023-05-16. The service was still in beta at that time.
```

2023-05-31 07:27 UTC, ulises-jeremias commented on examples/klotho-analysis/README.md
> +- [Klotho Docks](https://klo.dev/)
```suggestion
- [Klotho Docs](https://klo.dev/)
```

2023-06-01 15:27 UTC, di3go-martinez commented on examples/klotho-analysis/klotho-go-example/README.md
> +curl -fsSL "http://srv.klo.dev/update/latest/linux/x86_64?stream=pro:latest" -o klotho
It´d be good to put the link to the official documentation where this way of installing is suggested (notice HTTP is not secured). it´d be worth trying out the docker image (https://hub.docker.com/r/klothoplatform/klotho)

2023-06-01 15:27 UTC, di3go-martinez commented on examples/klotho-analysis/klotho-go-example/README.md
> +sudo chmod +x klotho
as long as the Klotho binary is located under any user's folder, sudo cmd is not required here

2023-06-01 15:29 UTC, di3go-martinez commented on examples/klotho-analysis/klotho-go-example/README.md
> +curl -fsSL "http://srv.klo.dev/update/latest/linux/x86_64?stream=pro:latest" -o klotho
It´d be good to put the link to the official documentation where this way of installing is suggested (notice HTTP is not secured). it´d be worth trying out the docker image (https://hub.docker.com/r/klothoplatform/klotho)

2023-07-13 17:09 UTC, ulises-jeremias approved these changes

2023-07-13 17:11 UTC, merged